### ISSUE TITLE
Cannot find module '.../node_modules/inote-util/lib/async-util'

### ISSUE THREAD

**Issue by ghost** [intellinote/inote-util#2] opened 2017-08-23 10:43 UTC
Hello,

I have a project that uses 'sql-client' (1.2.2), which in turn references 'inote-util':

    node_modules/sql-client/lib/sql-runner.js:9

It looks like 'inote-util' was recently updated from version 1.9.2 to 1.9.6, which is now causing the following exception to be thrown whenever I require('sql-client'):

    Cannot find module '.../node_modules/inote-util/lib/async-util'

If I pin the dependency on 'inote-util' to the old version (ie 1.9.2) then everything works fine.

I'm not sure what's causing the underlying problem, but when version 1.9.6 is installed node_modules only holds a 'async-util.coffee' file and NOT a 'async-util.js' file - is this be an compilation / packaging issue?

**Comment by joncodo** [comment] 2017-08-23 11:51
Looking into this now. It looks like a compilation error

**Comment by joncodo** [comment] 2017-08-23 12:23
So I ran `make coffee` on this branch and all the files were generated. I think that is what you need. However, when I tried to check that in, I see that we have *.js in the `.gitignore`. What is the reason these are not checked in @rodw ? Is the expected behaviour that each person builds the js files themselves? Maybe we should check them in?

**Comment by rodw** [comment] 2017-08-30 01:02
No, the expected behavior is that clients of inote-util obtain the code from npm, which should have the *.js files already due to the behavior of `make module`.

It sounds like maybe the latest build pushed to npm wasn't right.

**Comment by rodw** [comment] 2017-08-30 23:29
Sorry for the bother. 

I've just pushed v1.10.0 to npm and confirmed that it does have the pre-generated *.js files.

Only the v1.9.6 version has/had this issue, you should be fine grabbing the latest version now.

Closing this issue; thanks for the report @dsommerville !

**Closed as completed by rodw** 2017-08-30 23:29 UTC

**Comment by ghost** [comment] 2017-08-31 19:03
No problem - glad to help!
